// Code generated by "stringer -type=Token"; DO NOT EDIT.

package lexer

import "strconv"

const _Token_name = "TEndOfSourceTInvalidTIntegerConstantTFloatConstantTStringLiteralTCharLiteralTEllipsisTRightShiftEqualTLeftShiftEqualTPlusEqualTMinusEqualTAsteriskEqualTSlashEqualTPercentEqualTAndEqualTXorEqualTOrEqualTRightShiftTLeftShiftTPlusPlusTMinusMinusTPointerDotTAndAndTOrOrTLessEqualTGreaterEqualTEqualEqualTNotEqualTSemicolonTCurlyBraceOpenTCurlyBraceCloseTCommaTColonTEqualTParenOpenTParenCloseTSquareBracketOpenTSquareBracketCloseTDotTAndTNotTBitNotTMinusTPlusTAsteriskTSlashTPercentTLessTGreaterTXorTOrTQuestionTIdentifierTAlignAsTAlignOfTAtomicTAutoTBitIntTBoolTBreakTCaseTCharTComplexTConstTConstExprTContinueTDecimal128TDecimal32TDecimal64TDefaultTDoTDoubleTElseTEnumTExternTFalseTFloatTForTGenericTGotoTIfTImaginaryTInlineTIntTLongTNoreturnTNullptrTRegisterTRestrictTReturnTShortTSignedTSizeofTStaticTStaticAssertTStructTSwitchTThreadLocalTTrueTTypedefTTypeofTTypeofUnqualTUnionTUnsignedTVoidTVolatileTWhile"

var _Token_index = [...]uint16{0, 12, 20, 36, 50, 64, 76, 85, 101, 116, 126, 137, 151, 162, 175, 184, 193, 201, 212, 222, 231, 242, 253, 260, 265, 275, 288, 299, 308, 318, 333, 349, 355, 361, 367, 377, 388, 406, 425, 429, 433, 437, 444, 450, 455, 464, 470, 478, 483, 491, 495, 498, 507, 518, 526, 534, 541, 546, 553, 558, 564, 569, 574, 582, 588, 598, 607, 618, 628, 638, 646, 649, 656, 661, 666, 673, 679, 685, 689, 697, 702, 705, 715, 722, 726, 731, 740, 748, 757, 766, 773, 779, 786, 793, 800, 813, 820, 827, 839, 844, 852, 859, 872, 878, 887, 892, 901, 907}

func (i Token) String() string {
	i -= 1
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
